steps:
  build:
    image: sh
    commands:
      - cargo build

  configure_power_supply:
    image: sh
    commands:
      # Sanity check: power supply replies to IDN command
      - python3 utils/control_power_supply.py '*IDN?'

      # For now, only provide power to one of the RPIs
      - python3 utils/control_power_supply.py 'VSET1:05.00'
      - python3 utils/control_power_supply.py 'VSET2:00.00'

  # All other steps are similar to this one, the only difference is
  # the flashed binary.
  flash_and_test_gpio_toggle_unsafe:
    image: sh
    commands:
      # Turn on the RPI
      - python3 utils/control_power_supply.py 'OUT1'

      # Flash it with specified binary
      - cargo flash --bin gpio_toggle_unsafe --release --chip RP2040 --probe 2e8a:000c:$DEBUG_PROBE_1_SERIAL

      # After flashing, do a power cycle to remove any configuration
      # done by previous steps.
      - python3 utils/control_power_supply.py 'OUT0'
      - python3 utils/control_power_supply.py 'OUT1'

      # Run the tests
      - pytest tests/test_gpio_toggle.py -v -s --capture_file=gpio_toggle_unsafe.csv

      # Turn off the RPI
      - python3 utils/control_power_supply.py 'OUT0'

  flash_and_test_gpio_toggle_with_pac:
    image: sh
    commands:
      - python3 utils/control_power_supply.py 'OUT1'
      - cargo flash --bin gpio_toggle_with_pac --release --chip RP2040 --probe 2e8a:000c:$DEBUG_PROBE_1_SERIAL
      - python3 utils/control_power_supply.py 'OUT0'
      - python3 utils/control_power_supply.py 'OUT1'
      - pytest tests/test_gpio_toggle.py -v -s --capture_file=gpio_toggle_with_pac.csv
      - python3 utils/control_power_supply.py 'OUT0'

  flash_and_test_gpio_toggle_with_hal:
    image: sh
    commands:
      - python3 utils/control_power_supply.py 'OUT1'
      - cargo flash --bin gpio_toggle_with_hal --release --chip RP2040 --probe 2e8a:000c:$DEBUG_PROBE_1_SERIAL
      - python3 utils/control_power_supply.py 'OUT0'
      - python3 utils/control_power_supply.py 'OUT1'
      - pytest tests/test_gpio_toggle.py -v -s --capture_file=gpio_toggle_with_hal.csv
      - python3 utils/control_power_supply.py 'OUT0'

  flash_and_test_pwm_with_hal:
    image: sh
    commands:
      - python3 utils/control_power_supply.py 'OUT1'
      - cargo flash --bin pwm_with_hal --release --chip RP2040 --probe 2e8a:000c:$DEBUG_PROBE_1_SERIAL
      - python3 utils/control_power_supply.py 'OUT0'
      - python3 utils/control_power_supply.py 'OUT1'
      - pytest tests/test_gpio_toggle.py -v -s --capture_file=pwm_with_hal.csv
      - python3 utils/control_power_supply.py 'OUT0'

  upload:
    image: sh
    commands: |
      plugin-s3 \
        --endpoint http://$MINIO_SERVER \
        --bucket embci-artifacts \
        --access-key $MINIO_ACCESS_KEY \
        --secret-key $MINIO_SECRET_KEY \
        --source 'output/*' \
        --target ${CI_REPO_NAME}_${CI_PIPELINE_NUMBER} \
        --path-style true
