pipeline:
  build:
    image: sh
    commands:
      - cargo build

  flash_gpio_toggle_unsafe:
    image: sh
    commands:
      - cargo flash --bin gpio_toggle_unsafe --release --chip RP2040

  test_gpio_toggle_unsafe:
    image: sh
    commands:
      - pytest tests/test_gpio_toggle.py -v -s

  flash_gpio_toggle_with_pac:
    image: sh
    commands:
      - cargo flash --bin gpio_toggle_with_pac --release --chip RP2040

  test_gpio_toggle_with_pac:
    image: sh
    commands:
      - pytest tests/test_gpio_toggle.py -v -s

  flash_gpio_toggle_with_hal:
    image: sh
    commands:
      - cargo flash --bin gpio_toggle_with_hal --release --chip RP2040

  test_gpio_toggle_with_hal:
    image: sh
    commands:
      - pytest tests/test_gpio_toggle.py -v -s

  # flash_pwm_with_hal:
  #   image: sh
  #   commands:
  #     - cargo flash --bin pwm_with_hal --release --chip RP2040
  #
  # test_pwm_with_hal:
  #   image: sh
  #   commands:
  #     - python3 saleae_example.py
  #     - mv output/digital.csv output/test_pwm_with_hal.csv
  #     - cat output/test_pwm_with_hal.csv
