[package]
name = "embci-example-repo"
version = "0.1.0"
edition = "2021"

[dependencies]
# https://docs.rs/cortex-m/0.7.7/cortex_m/index.html
cortex-m = "0.7.7"

# https://docs.rs/cortex-m-rt/0.7.3/cortex_m_rt/index.html
cortex-m-rt = "0.7.3"

# https://docs.rs/panic-halt/0.2.0/panic_halt/index.html
panic-halt = "0.2.0"
